(function(){
'use strict';
function load(src,id){if(document.getElementById(id))return;var s=document.createElement('script');s.id=id;s.src=src;document.body.appendChild(s);}
function mergeStandardTime(){var a=document.getElementById('standard-time');if(!a)return;var p=[].slice.call(a.querySelectorAll('p'));for(var i=0;i<p.length-1;i++){var x=p[i].textContent.trim(),y=p[i+1].textContent.trim();if(x.indexOf('第一，用于产能测算')>-1&&x.indexOf('第三，用于线平衡改善')>-1&&y.indexOf('第四，用于ERP/MES基础数据')>-1&&y.indexOf('第五，用于经营改善分析')>-1){p[i].textContent=(x+' '+y).replace(/\s+/g,' ');p[i+1].remove();break;}}}
function mergeVisualPrinciples(){var a=document.getElementById('visual');if(!a||a.dataset.visualPrinciplesMerged==='1')return;var p=[].slice.call(a.querySelectorAll('p'));for(var i=0;i<p.length-1;i++){var x=(p[i].textContent||'').trim(),y=(p[i+1].textContent||'').trim();if(x.indexOf('第一，少而准')===0&&x.indexOf('第二，统一')>-1&&y.indexOf('第三，可维护')===0&&y.indexOf('第四，能闭环')>-1){p[i].textContent=(x+' '+y).replace(/\s+/g,' ').trim();p[i+1].remove();a.dataset.visualPrinciplesMerged='1';break;}}}
function ensurePlatformPositioning(){if(!/home\.html$|digital_human\/?$/i.test(location.pathname)||document.getElementById('platformPositioning'))return;var hero=document.querySelector('.hero');if(!hero)return;var h1=hero.querySelector('h1');if(!h1)return;var p=document.createElement('p');p.id='platformPositioning';p.className='platform-positioning';p.textContent='制造改善实践交流平台｜项目案例｜知识分享｜方法工具';h1.insertAdjacentElement('afterend',p);var st=document.createElement('style');st.id='platformPositioningStyle';st.textContent='.platform-positioning{display:inline-flex;max-width:100%;margin:2px 0 12px;padding:7px 13px;border:1px solid rgba(255,227,155,.58);color:#fff3df;background:rgba(255,255,255,.08);font-size:16px!important;line-height:1.55!important;font-weight:850;letter-spacing:.02em}@media(max-width:760px){.platform-positioning{display:block;font-size:15px!important;padding:7px 10px}}';document.head.appendChild(st);}
function copyText(t){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(t);var a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.left='-9999px';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();return Promise.resolve();}
function shortShareUrl(){var map={'home.html':'','daily-insights.html':'daily.html','papers.html':'papers.html','lean-tools.html':'tools.html','lean-knowledge.html':'knowledge.html','execution-loop.html':'execution.html','gbt2828.html':'gbt2828.html'};var name=(location.pathname.split('/').pop()||'home.html').toLowerCase();var shortPath=Object.prototype.hasOwnProperty.call(map,name)?map[name]:name;return 'https://qilylean.com/'+shortPath+(location.search||'')+(location.hash||'');}
function initDock(){if(document.getElementById('floatDock'))return;var st=document.createElement('style');st.textContent='.float-dock{position:fixed;right:18px;bottom:86px;z-index:9999;display:flex;flex-direction:column;gap:10px;touch-action:none;user-select:none;-webkit-user-select:none}.float-btn{width:64px;height:64px;border:0;border-radius:50%;font-weight:900;box-shadow:0 12px 28px rgba(15,75,90,.28);cursor:pointer;-webkit-tap-highlight-color:transparent;touch-action:none}.float-btn:active{transform:scale(.96)}.float-home{background:#0f6671;color:#fff}.float-share{background:#8e4774;color:#fff}.float-wx{background:#f5c861;color:#17322d}.wx-mask,.share-mask{position:fixed;inset:0;z-index:10000;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.42);padding:20px}.wx-mask.show,.share-mask.show{display:flex}.wx-panel,.share-panel{position:relative;width:min(92vw,460px);max-height:90vh;overflow:auto;padding:24px;background:#fff;border-radius:20px;text-align:center}.wx-close,.share-close{position:absolute;right:12px;top:10px;width:34px;height:34px;border:0;border-radius:50%}.share-brand{font-size:22px;font-weight:950;color:#0f4b5a}.wx-copy-btn,.share-action{padding:10px 14px;border:0;border-radius:10px;background:#0f4b5a;color:#fff;font-weight:850}.share-url{display:block;margin:12px 0;padding:10px 12px;border:1px solid #d5e4e3;border-radius:10px;color:#355;word-break:break-all;background:#f6fbfa;font-size:14px;line-height:1.6}.share-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}.share-note{margin:8px 0 0;color:#5f7474;font-size:14px}.share-action.secondary{background:#8e4774}';document.head.appendChild(st);
var d=document.createElement('div');d.id='floatDock';d.className='float-dock';d.innerHTML='<button class="float-btn float-home" data-a="home" aria-label="返回首页">首页</button><button class="float-btn float-share" data-a="share" aria-label="分享当前页面">分享</button><button class="float-btn float-wx" data-a="contact" aria-label="交流">交流</button>';document.body.appendChild(d);
var m=document.createElement('div');m.id='wxMask';m.className='wx-mask';m.innerHTML='<div class="wx-panel"><button class="wx-close" aria-label="关闭">×</button><h3>交流</h3><div class="wx-qr-host"></div><p><strong>Qily259</strong></p><button class="wx-copy-btn">复制微信号</button></div>';document.body.appendChild(m);
var sm=document.createElement('div');sm.id='shareMask';sm.className='share-mask';sm.innerHTML='<div class="share-panel"><button class="share-close" aria-label="关闭">×</button><div class="share-brand">QilyLean</div><h3>分享当前页面</h3><span class="share-url"></span><div class="share-actions"><button class="share-action secondary" data-share="system">系统分享</button><button class="share-action" data-share="copy">复制网址</button></div><p class="share-note">分享内容将使用 QilyLean 短地址。</p></div>';document.body.appendChild(sm);
var down=false,moved=false,sx=0,sy=0,sl=0,stp=0,action='',pid=null;
function runAction(){if(action==='home'){if(/home\.html$|digital_human\/?$/i.test(location.pathname))scrollTo({top:0,behavior:'smooth'});else location.href='home.html'}else if(action==='share'){sm.querySelector('.share-url').textContent=shortShareUrl();sm.classList.add('show')}else if(action==='contact'){m.classList.add('show')}}
d.addEventListener('pointerdown',function(e){var b=e.target.closest('.float-btn');if(!b)return;down=true;moved=false;action=b.getAttribute('data-a')||'';pid=e.pointerId;var r=d.getBoundingClientRect();sx=e.clientX;sy=e.clientY;sl=r.left;stp=r.top;d.style.left=sl+'px';d.style.top=stp+'px';d.style.right='auto';d.style.bottom='auto';if(d.setPointerCapture)d.setPointerCapture(pid);e.preventDefault();},{passive:false});
d.addEventListener('pointermove',function(e){if(!down||e.pointerId!==pid)return;var dx=e.clientX-sx,dy=e.clientY-sy;if(!moved&&Math.hypot(dx,dy)>12)moved=true;if(!moved)return;e.preventDefault();d.style.left=Math.max(8,Math.min(innerWidth-d.offsetWidth-8,sl+dx))+'px';d.style.top=Math.max(8,Math.min(innerHeight-d.offsetHeight-8,stp+dy))+'px';},{passive:false});
function finish(e,cancelled){if(!down||e.pointerId!==pid)return;down=false;try{if(d.releasePointerCapture)d.releasePointerCapture(pid)}catch(_e){}var shouldRun=!cancelled&&!moved;pid=null;if(shouldRun)runAction();}
d.addEventListener('pointerup',function(e){finish(e,false)});d.addEventListener('pointercancel',function(e){finish(e,true)});
m.querySelector('.wx-close').onclick=function(){m.classList.remove('show')};m.onclick=function(e){if(e.target===m)m.classList.remove('show')};m.querySelector('.wx-copy-btn').onclick=function(){copyText('Qily259')};
sm.querySelector('.share-close').onclick=function(){sm.classList.remove('show')};sm.onclick=function(e){if(e.target===sm)sm.classList.remove('show')};sm.querySelector('[data-share="copy"]').onclick=function(){copyText(shortShareUrl()).then(function(){sm.querySelector('.share-note').textContent='当前页面短网址已复制。'})};sm.querySelector('[data-share="system"]').onclick=function(){var u=shortShareUrl(),t=document.title||'QilyLean';if(navigator.share)navigator.share({title:t,url:u}).catch(function(){});else copyText(t+'\n'+u).then(function(){sm.querySelector('.share-note').textContent='当前页面短网址已复制。'})};}
function boot(){load('terminology-v2.js?v=5','terminologyV2Script');load('wechat-qr-official.js?v=4','wechatQrOfficialScript');load('execution-loop-entry.js?v=1','executionLoopEntryScript');load('lean-tools-entry.js?v=1','leanToolsEntryScript');load('daily-2026-07-15.js?v=1','daily20260715Script');load('daily-2026-07-16.js?v=1','daily20260716Script');mergeStandardTime();mergeVisualPrinciples();ensurePlatformPositioning();initDock();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();