(function(){
const HOME='home.html',WECHAT='Qily259';
function copyText(t){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(t);return new Promise((r,j)=>{try{const i=document.createElement('input');i.value=t;i.style.position='fixed';i.style.left='-9999px';document.body.appendChild(i);i.select();document.execCommand('copy');i.remove();r();}catch(e){j(e);}})}
function toast(t){let e=document.getElementById('floatToast');if(!e){e=document.createElement('div');e.id='floatToast';e.className='float-toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function clamp(el,l,t){const m=8;return{left:Math.min(Math.max(m,l),Math.max(m,innerWidth-el.offsetWidth-m)),top:Math.min(Math.max(m,t),Math.max(m,innerHeight-el.offsetHeight-m))}}
function drag(el,key,handle){if(!el||el.dataset.uiDrag==='1')return;el.dataset.uiDrag='1';let d=false,m=false,sx=0,sy=0,sl=0,st=0;try{const p=JSON.parse(localStorage.getItem(key)||'null');if(p){const q=clamp(el,p.left,p.top);el.style.left=q.left+'px';el.style.top=q.top+'px';el.style.right='auto';el.style.bottom='auto'}}catch(e){}el.addEventListener('pointerdown',e=>{if(!e.target.closest(handle)||e.target.closest('input,select,textarea,a'))return;d=true;m=false;const r=el.getBoundingClientRect();sx=e.clientX;sy=e.clientY;sl=r.left;st=r.top;el.style.left=sl+'px';el.style.top=st+'px';el.style.right='auto';el.style.bottom='auto';try{el.setPointerCapture(e.pointerId)}catch(x){}});el.addEventListener('pointermove',e=>{if(!d)return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>4||Math.abs(dy)>4)m=true;if(!m)return;e.preventDefault();const p=clamp(el,sl+dx,st+dy);el.style.left=p.left+'px';el.style.top=p.top+'px'});el.addEventListener('pointerup',e=>{if(!d)return;d=false;try{el.releasePointerCapture(e.pointerId)}catch(x){}if(m){const r=el.getBoundingClientRect();localStorage.setItem(key,JSON.stringify({left:r.left,top:r.top}));e.preventDefault();e.stopPropagation()}})}
function ensureVoiceDockButton(){
  const d=document.getElementById('floatDock');if(!d)return null;
  let b=document.getElementById('floatVoiceBtn');
  if(!b){b=document.createElement('button');b.id='floatVoiceBtn';b.className='float-btn float-voice';b.dataset.action='voice';b.innerHTML='<span class="float-icon">声</span><span class="float-text">语音播报</span>';d.appendChild(b)}
  if(!document.getElementById('uiManagerVoiceStyle')){const s=document.createElement('style');s.id='uiManagerVoiceStyle';s.textContent='.float-voice{color:#17322d;background:linear-gradient(135deg,#d8f2ef,#8bd4cc)}.float-voice.active{box-shadow:0 0 0 3px rgba(139,212,204,.45),0 12px 30px rgba(15,75,90,.28)}';document.head.appendChild(s)}
  return b;
}
function setVoiceCollapsed(collapsed){
  const c=document.getElementById('voiceCard'),m=document.getElementById('voiceMini'),b=ensureVoiceDockButton();
  if(m)m.style.display='none';
  if(c)c.style.display=collapsed?'none':'block';
  if(b)b.classList.toggle('active',!collapsed);
  try{localStorage.setItem('voiceClosed',collapsed?'1':'0')}catch(e){}
}
function repairDock(){const d=document.getElementById('floatDock');if(!d)return;ensureVoiceDockButton();if(d.dataset.uiManager==='1')return;d.dataset.uiManager='1';d.style.touchAction='none';drag(d,'floatDockPos','.float-dock,.float-btn');let action='',moved=false,sx=0,sy=0;d.onclick=null;d.addEventListener('pointerdown',e=>{const b=e.target.closest('.float-btn');if(!b)return;action=b.dataset.action||b.dataset.a||'';moved=false;sx=e.clientX;sy=e.clientY});d.addEventListener('pointermove',e=>{if(action&&(Math.abs(e.clientX-sx)>4||Math.abs(e.clientY-sy)>4))moved=true});d.addEventListener('pointerup',()=>{if(!action)return;const a=action;action='';if(moved)return;if(a==='home'){if(/\/home\.html$|\/digital_human\/?$/i.test(location.pathname))scrollTo({top:0,behavior:'smooth'});else location.href=HOME}else if(a==='share'){const u=location.href.split('#')[0];navigator.share?navigator.share({title:document.title,url:u}).catch(()=>{}):copyText(document.title+'\n'+u).then(()=>toast('链接已复制'))}else if(a==='contact'){document.getElementById('wxMask')?.classList.add('show')}else if(a==='voice'){const c=document.getElementById('voiceCard');const closed=!c||c.style.display==='none'||getComputedStyle(c).display==='none';setVoiceCollapsed(!closed)}});d.addEventListener('click',e=>{e.preventDefault();e.stopPropagation()},true)}
function repairContact(){const m=document.getElementById('wxMask');if(!m)return;const close=document.getElementById('wxCloseBtn');if(close)close.onclick=e=>{e.preventDefault();e.stopPropagation();m.classList.remove('show')};m.onclick=e=>{if(e.target===m)m.classList.remove('show')};const b=document.getElementById('copyWxBtn');if(b&&b.dataset.uiManager!=='1'){b.dataset.uiManager='1';b.textContent='复制微信号并打开微信';b.onclick=e=>{e.preventDefault();e.stopPropagation();copyText(WECHAT).then(()=>{toast('微信号已复制，正在打开微信…');location.href='weixin://'}).catch(()=>{location.href='weixin://'})}}}
function repairVoice(){const c=document.getElementById('voiceCard'),m=document.getElementById('voiceMini');drag(c,'voicePos','.voice-head');if(m)m.style.display='none';[c].forEach(e=>{if(e)e.style.touchAction='none'});['voicePlay','voicePause','voiceStop'].forEach(id=>{const b=document.getElementById(id);if(b)b.style.pointerEvents='auto'});const close=document.getElementById('voiceClose');if(close&&close.dataset.uiManager!=='1'){close.dataset.uiManager='1';close.onclick=e=>{e.preventDefault();e.stopPropagation();if(window.speechSynthesis)speechSynthesis.cancel();setVoiceCollapsed(true)}}let closed=false;try{closed=localStorage.getItem('voiceClosed')==='1'}catch(e){}setVoiceCollapsed(closed)}
function clean(){document.querySelectorAll('.tag,.tags li,li,span').forEach(e=>{if((e.textContent||'').trim()==='退役军人')e.remove()})}
function apply(){clean();repairDock();repairContact();repairVoice()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();
setTimeout(apply,300);setTimeout(apply,900);setTimeout(apply,1800);new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});
})();